name: ğŸ”¨ Flutter APK Builder

on:
  push:
    branches: [master]

jobs:
  build-apk:
    if: contains(github.event.head_commit.message, 'apkbuild')
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ” Checkout source code
        uses: actions/checkout@v3

      - name: ğŸ’¾ Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: ğŸ“¦ Get Dependencies
        run: flutter pub get

      - name: ğŸ› ï¸ Build APK
        run: flutter build apk --release

      - name: â˜ï¸ Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Flutter-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk
